// Compact airline comparison data, optimised for the /airlines-compared page.
// Maintained alongside the master AIRLINES list in components/PetTravel.jsx.
// When you update an airline's carrier, weight, fee, or cabin status here,
// also update the matching entry in PetTravel.jsx (and vice versa).
//
// cabinStatus values: "yes" (cabin pets allowed broadly),
//   "conditional" (allowed on some routes but with significant exclusions),
//   "no" (cargo only or no pets at all).
//
// brachy: short description of brachycephalic (snub-nosed) policy.

export const AIRLINES_COMPARE = [
  {
    name: "Alaska Airlines",
    carrier: "Soft: 17×11×9.5 in. Hard: 17×11×7.5 in",
    weight: "No stated weight limit; pet must fit comfortably",
    fee: "$100 each way",
    cabinStatus: "yes",
    intl: "Limited (Americas)",
    brachy: "Allowed in cabin where airline operates",
    ukOut: false,
    notes: "Strong US-domestic + Mexico/Canada/Costa Rica. Hawaii with strict DAR prep. Two same-species pets can share one carrier.",
    verified: "May 2026",
    link: "https://www.alaskaair.com/content/travel-info/policies/pets-traveling-with-pets",
  },
  {
    name: "American Airlines",
    carrier: "Soft: 18×11×11 in. Hard: 19×13×9 in",
    weight: "Pet + carrier max 20 lb (~9 kg) combined",
    fee: "$150 each way",
    cabinStatus: "conditional",
    intl: "Limited (Americas + Caribbean)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "NOT transatlantic / transpacific in cabin. Domestic US, Canada, Mexico, Caribbean, Central America (≤12h flights).",
    verified: "May 2026",
    link: "https://www.aa.com/i18n/travel-info/special-assistance/traveling-with-pets.jsp",
  },
  {
    name: "Delta",
    carrier: "Soft-sided ~18×11×11 in. 3+ ventilation panels (4 intl)",
    weight: "No stated weight; must fit under seat",
    fee: "$150 domestic / $200 international",
    cabinStatus: "conditional",
    intl: "Yes (restricted country list)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Many country exclusions (UK, AU, NZ, UAE, HK, Hawaii, Ireland, Brazil, Colombia, South Africa, Jamaica, Iceland, etc.). JFK→CDG works.",
    verified: "May 2026",
    link: "https://www.delta.com/us/en/pet-travel/overview",
  },
  {
    name: "United",
    carrier: "Soft: 18×11×11 in. Hard: 17.5×12×7.5 in",
    weight: "No stated weight; must fit under seat",
    fee: "$150 each way",
    cabinStatus: "conditional",
    intl: "Yes (incl. US ↔ Japan)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Rare cabin option for US↔Japan direct (SFO/ORD↔NRT/HND/KIX). Long excluded-country list otherwise.",
    verified: "May 2026",
    link: "https://www.united.com/en/us/fly/travel/traveling-with-pets.html",
  },
  {
    name: "JetBlue",
    carrier: "Soft: 17×12.5×8.5 in",
    weight: "Pet + carrier max 20 lb (strictly enforced)",
    fee: "$125 each way",
    cabinStatus: "conditional",
    intl: "Limited (Americas)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Domestic US + Caribbean + some Latin America. No extra-legroom seats for pets.",
    verified: "May 2026",
    link: "https://www.jetblue.com/help/jetpaws",
  },
  {
    name: "Air Canada",
    carrier: "Soft: 21.5×15.5×9 in. Hard: 23×15×10.5 in",
    weight: "Pet + carrier max 10 kg (22 lb)",
    fee: "CAD 50–100 domestic / CAD 270–320 international",
    cabinStatus: "yes",
    intl: "Yes",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "ONE of the very few airlines that flies cabin pets OUT of the UK (LHR). Strong UK/Canada/US/Europe network.",
    verified: "May 2026",
    link: "https://www.aircanada.com/us/en/aco/home/plan/special-assistance/pets.html",
  },
  {
    name: "Air Transat",
    carrier: "Soft: 16×9.5×8.5 in",
    weight: "Pet + carrier max 10 kg (22 lb)",
    fee: "CAD 50–100",
    cabinStatus: "yes",
    intl: "Yes (transatlantic from MAN/YYZ)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "Cabin pets from Manchester (MAN) and Glasgow (GLA). NOT from Gatwick. Useful UK→Canada route.",
    verified: "May 2026",
    link: "https://www.airtransat.com/en-CA/travel-information/special-assistance/travelling-with-pets",
  },
  {
    name: "Air France",
    carrier: "Combined L+W+H ≤ 46 cm + 28 + 24 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€75–200",
    cabinStatus: "yes",
    intl: "Yes (excellent global cabin coverage)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "One of the strongest cabin pet airlines worldwide. LHR/MAN to Paris CDG in cabin. Onward to USA/Asia in cabin.",
    verified: "May 2026",
    link: "https://www.airfrance.us/US/en/local/guidevoyageur/pratique/animaux_pratique_airfrance.htm",
  },
  {
    name: "KLM",
    carrier: "Combined L+W+H ≤ 46 cm + 28 + 24 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€75–200",
    cabinStatus: "yes",
    intl: "Yes (strong cabin network)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "LHR to Amsterdam Schiphol in cabin. Onward via AMS to most KLM destinations.",
    verified: "May 2026",
    link: "https://www.klm.com/information/legal/conditions-carriage-pets",
  },
  {
    name: "Lufthansa",
    carrier: "Soft: 55×40×23 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€75–200",
    cabinStatus: "yes",
    intl: "Yes (large hub network)",
    brachy: "Allowed in cabin (some breed restrictions)",
    ukOut: true,
    notes: "LHR→FRA/MUC cabin pets. Strong onward connections to India, USA, Asia.",
    verified: "May 2026",
    link: "https://www.lufthansa.com/us/en/dogs-and-cats-in-the-cabin",
  },
  {
    name: "SWISS",
    carrier: "Soft: 55×40×23 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€75–200",
    cabinStatus: "yes",
    intl: "Yes",
    brachy: "ALLOWED in cabin (rare — most airlines refuse cargo for these)",
    ukOut: true,
    notes: "Uniquely permits brachycephalic breeds in cabin where most airlines refuse cargo. LHR→ZRH→onward.",
    verified: "May 2026",
    link: "https://www.swiss.com/us/en/prepare/baggage/dogs-cats-and-other-animals",
  },
  {
    name: "TAP Air Portugal",
    carrier: "Soft: 39×33×17 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€55–150",
    cabinStatus: "yes",
    intl: "Yes (UK + Europe + Brazil + USA)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "LHR→LIS cabin route. Solid onward to USA and Brazil.",
    verified: "May 2026",
    link: "https://www.flytap.com/en-us/special-care/traveling-with-animals",
  },
  {
    name: "Iberia",
    carrier: "Soft: 45×35×25 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€55–150",
    cabinStatus: "yes",
    intl: "Yes (Spain + Europe + Americas)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Strong Spain+Latin America cabin network. No UK departures (LHR not in their cabin policy).",
    verified: "May 2026",
    link: "https://www.iberia.com/us/special-luggage/animals/",
  },
  {
    name: "Vueling",
    carrier: "Soft: 45×39×21 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€40–60",
    cabinStatus: "yes",
    intl: "Europe only",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "One of the cheapest cabin pet airlines in Europe. Book via 'Fly Light' fare. No UK or Iceland routes.",
    verified: "May 2026",
    link: "https://www.vueling.com/en/we-are-different/services/pets",
  },
  {
    name: "ITA Airways",
    carrier: "Soft: 24×40×20 cm",
    weight: "Pet + carrier max 10 kg combined",
    fee: "€50–250",
    cabinStatus: "yes",
    intl: "Yes (Italy + Europe + Americas)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "Cabin LHR→FCO. Solid onward to USA and South America. Successor to Alitalia.",
    verified: "May 2026",
    link: "https://www.ita-airways.com/en_it/fly-ita/special-luggage/pets.html",
  },
  {
    name: "Turkish Airlines",
    carrier: "Soft: 55×40×23 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "$75–200",
    cabinStatus: "yes",
    intl: "Yes (huge global network)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "LHR→IST cabin. One of the world's biggest cabin pet networks via Istanbul hub.",
    verified: "May 2026",
    link: "https://www.turkishairlines.com/en-int/any-questions/traveling-with-pets/",
  },
  {
    name: "LOT Polish Airlines",
    carrier: "Soft: 55×40×23 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€60–200",
    cabinStatus: "yes",
    intl: "Yes (Europe + USA)",
    brachy: "Allowed in cabin",
    ukOut: true,
    notes: "LHR→WAW cabin. Onward to USA and Asia.",
    verified: "May 2026",
    link: "https://www.lot.com/us/en/animals",
  },
  {
    name: "SAS",
    carrier: "Soft: 40×25×23 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€70–200",
    cabinStatus: "yes",
    intl: "Yes (Europe + USA + Asia)",
    brachy: "Some breed restrictions by destination",
    ukOut: false,
    notes: "Cabin in/out of Copenhagen, Stockholm, Oslo. Doesn't fly UK→cabin pets. Special rules for Iceland, Svalbard.",
    verified: "May 2026",
    link: "https://www.flysas.com/en/travel-info/special-needs/travelling-with-pet/",
  },
  {
    name: "Finnair",
    carrier: "Soft: 43×31×20 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "€60–200",
    cabinStatus: "yes",
    intl: "Yes (Europe + Asia)",
    brachy: "Some breed restrictions",
    ukOut: false,
    notes: "Helsinki hub. Good Asia connections. Some breed restrictions by route.",
    verified: "May 2026",
    link: "https://www.finnair.com/en/travel-information/special-baggage/travelling-with-pets",
  },
  {
    name: "Etihad",
    carrier: "Soft / hard: ~50×40×30 cm (varies)",
    weight: "Pet + carrier max 8 kg",
    fee: "AED 700–1500",
    cabinStatus: "conditional",
    intl: "Yes (to Abu Dhabi only)",
    brachy: "Restricted — confirm by phone",
    ukOut: false,
    notes: "Cabin pets only to/from Abu Dhabi (AUH), NOT Dubai. Book by phone — not online. UAE permit required.",
    verified: "May 2026",
    link: "https://www.etihad.com/en/help/baggage/travelling-with-pets",
  },
  {
    name: "Air India",
    carrier: "Soft: 45×30×25 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "INR 4,000–20,000",
    cabinStatus: "conditional",
    intl: "Yes (NOT to USA/UK/Canada/Australia)",
    brachy: "Some restrictions — confirm",
    ukOut: false,
    notes: "Only major Indian carrier with cabin pets. NOT cabin to USA, UK, Canada, Australia. Route via European hub for those.",
    verified: "May 2026",
    link: "https://www.airindia.com/in/en/travel-information/special-assistance/travelling-with-animals.html",
  },
  {
    name: "LATAM",
    carrier: "Soft: 36×33×23 cm",
    weight: "Pet + carrier max 10 kg combined",
    fee: "$75–200",
    cabinStatus: "yes",
    intl: "Yes (within South America + to USA)",
    brachy: "Allowed in cabin (not hold)",
    ukOut: false,
    notes: "Primary South America cabin pet carrier. LATAM-operated flights ONLY — codeshares void the booking. Book by phone/WhatsApp.",
    verified: "May 2026",
    link: "https://www.latamairlines.com/us/en/travel-information/special-luggage/pets",
  },
  {
    name: "Avianca",
    carrier: "Soft: 35×30×20 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "$75–150",
    cabinStatus: "yes",
    intl: "Yes (Americas)",
    brachy: "Some breed restrictions",
    ukOut: false,
    notes: "Strong Colombia and Central America cabin network. Bogotá hub.",
    verified: "May 2026",
    link: "https://www.avianca.com/us/en/before-your-trip/baggage-information/travel-pets/",
  },
  {
    name: "Copa Airlines",
    carrier: "Soft: ~46×28×23 cm",
    weight: "Pet + carrier max 9 kg combined",
    fee: "$125",
    cabinStatus: "yes",
    intl: "Yes (Americas via Panama hub)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Panama City (PTY) hub — key for reaching Uruguay, Paraguay, Bolivia in cabin.",
    verified: "May 2026",
    link: "https://www.copaair.com/en/web/us/pets",
  },
  {
    name: "Aeromexico",
    carrier: "Soft: 45×38×20 cm",
    weight: "Pet + carrier max 9 kg combined",
    fee: "$100–150",
    cabinStatus: "yes",
    intl: "Yes (incl. Mexico↔Japan)",
    brachy: "Allowed in cabin (NOT in cargo)",
    ukOut: false,
    notes: "Rare Mexico↔Japan cabin route (MEX↔NRT). Brachy breeds in cabin only, not cargo.",
    verified: "May 2026",
    link: "https://aeromexico.com/en-us/travel-information/special-services/travel-with-pets",
  },
  {
    name: "Volaris",
    carrier: "Soft: 45×34×23 cm",
    weight: "Pet + carrier max 10 kg combined",
    fee: "$70–150",
    cabinStatus: "conditional",
    intl: "Yes (Americas)",
    brachy: "BANNED entirely (cabin and cargo)",
    ukOut: false,
    notes: "Long banned-breed list including all brachycephalic dogs and cats, pit bull types, mastiffs. Cheaper but stricter than Aeromexico.",
    verified: "May 2026",
    link: "https://cms.volaris.com/en/travel-info/special-services/traveling-with-pets/",
  },
  {
    name: "Korean Air",
    carrier: "Soft: 45×30×23 cm",
    weight: "Pet + carrier max 7 kg combined",
    fee: "$100–200",
    cabinStatus: "yes",
    intl: "Yes (Korea + USA + Asia)",
    brachy: "Allowed with restrictions",
    ukOut: false,
    notes: "Strong Korea↔USA cabin option. ICN hub. Lower weight limit than most (7kg not 8kg).",
    verified: "May 2026",
    link: "https://www.koreanair.com/us/en/airport/baggage/pet",
  },
  {
    name: "Asiana",
    carrier: "Soft: 45×26×26 cm",
    weight: "Pet + carrier max 7 kg combined",
    fee: "$200",
    cabinStatus: "yes",
    intl: "Yes (Korea + USA + Asia)",
    brachy: "Some restrictions",
    ukOut: false,
    notes: "Second major Korean cabin pet option alongside Korean Air. ICN hub.",
    verified: "May 2026",
    link: "https://flyasiana.com/C/US/EN/contents/pet-transport",
  },
  {
    name: "Hawaiian Airlines",
    carrier: "Soft: ~40×30×20 cm",
    weight: "Pet + carrier max 25 lb",
    fee: "$35–125",
    cabinStatus: "yes",
    intl: "Limited (US + Japan + some Pacific)",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "Only meaningful cabin option OUT of Hawaii. Direct Airport Release prep required for entry into Hawaii — start 4+ months ahead.",
    verified: "May 2026",
    link: "https://www.hawaiianairlines.com/our-services/special-assistance/traveling-with-pets",
  },
  {
    name: "Lift Airline",
    carrier: "Soft: 40×30×20 cm",
    weight: "Pet + carrier max 8 kg",
    fee: "ZAR 500",
    cabinStatus: "yes",
    intl: "Domestic South Africa only",
    brachy: "Allowed in cabin",
    ukOut: false,
    notes: "ONLY domestic South Africa. No international cabin pets. (South Africa has no international cabin pet airline at all — cargo is the only way in/out.)",
    verified: "May 2026",
    link: "https://www.lift.co.za/",
  },
  {
    name: "British Airways",
    carrier: "—",
    weight: "—",
    fee: "Cargo only",
    cabinStatus: "no",
    intl: "Yes (cargo only)",
    brachy: "Cargo only — many breed exclusions",
    ukOut: false,
    notes: "Service / assistance dogs only in cabin. All other pets travel as manifested cargo via IAG Cargo.",
    verified: "May 2026",
    link: "https://www.britishairways.com/en-us/information/travel-assistance/travelling-with-pets",
  },
  {
    name: "Emirates",
    carrier: "—",
    weight: "—",
    fee: "Cargo only",
    cabinStatus: "no",
    intl: "Yes (cargo only)",
    brachy: "Cargo only — restrictions apply",
    ukOut: false,
    notes: "No cabin pets except falcons on specific Pakistan routes. All dogs/cats travel as Emirates SkyCargo manifested cargo.",
    verified: "May 2026",
    link: "https://www.emirates.com/english/help/topics/travelling-with-pets/",
  },
  {
    name: "Qatar Airways",
    carrier: "—",
    weight: "—",
    fee: "Cargo only",
    cabinStatus: "no",
    intl: "Yes (cargo only)",
    brachy: "Cargo only — restrictions apply",
    ukOut: false,
    notes: "No cabin pets except guide/assistance dogs. All other pets via Qatar Airways Cargo.",
    verified: "May 2026",
    link: "https://www.qatarairways.com/en/baggage/pet-travel.html",
  },
];
